Narrative:
In order to test fully toggle feature user first wants to fill game board then clean it.

Scenario: Fill game board with crosses
Given a 5 by 5 game
When I toggle the cell at (2, 3)
Then the grid should look like
.....
.....
.....
..X..
.....
When I toggle the cell at (2, 4)
Then the grid should look like
.....
.....
.....
..X..
..X..
When I toggle the cell at (2, 2)
Then the grid should look like
.....
.....
..X..
..X..
..X..

Scenario: Clean partially filled game board

When I toggle the cell at (2, 3)
Then the grid should look like
.....
.....
..X..
.....
..X..
When I toggle the cell at (2, 4)
Then the grid should look like
.....
.....
..X..
.....
.....
When I toggle the cell at (2, 2)
Then the grid should look like
.....
.....
.....
.....
.....