name: Run tests for fun1

on:
  push:
    paths:
      - 'fun1/**'
      - '.github/workflows/fun1.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: cd fun1 && mvn clean install